import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'
import Sidebar from './_components/sidebar'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen bg-slate-50">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
